### ISSUE TITLE
Error: cleartext http traffic to not permitted

### ISSUE THREAD

**Issue by dcasado** [39aldo39/spaRSS-DecSync#1]
I'm trying to add a RSS feed with http instead of https and the app crash when synchronising. When I open it again it shows this error: cleartext http traffic to not permitted. Maybe related to this? [Android 8: Cleartext HTTP traffic not permitted](https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted)

![photo_2018-12-19_21-00-40](https://user-images.githubusercontent.com/10188511/50244704-e44f6480-03d0-11e9-8277-02407f121179.jpg)

Phone: OnePlus 6
Android 9

**Comment by 39aldo39** [comment]
Thanks for the nice report. Your link indeed fixes the problem. I also noticed that the end of the refresh animation crashed on Android 9, so I fixed that as well. The animation is a bit less pretty, but I don't know how to fix it, as I have no experience with it.
