### ISSUE TITLE
Crashes on launch

### ISSUE THREAD

**Issue by poperigby** [39aldo39/spaRSS-DecSync#10]
On v1.14.0, the app crashes every time I try to open it.

**Comment by 39aldo39** [comment]
Yes, I noticed it as well. Actually, the current implementation of the Storage Access Framework is just way, way too slow, so the app doesn't respond. Until I know how to fix it, I just reverted the change and updated the version.

**Comment by poperigby** [comment]
Huh. Strange.

**Comment by 39aldo39** [comment]
I have re-added more efficient support for SAF, so the app doesn't crash anymore because it fast enough. More importantly, the app only uses it when absolutely necessary, as it is still very slow.
