### ISSUE TITLE
Error on load/refresh rss feed with ssl.

### ISSUE THREAD

**Issue by rakshazi** [39aldo39/spaRSS-DecSync#11]
Hello!

I'm trying to import `https://wowlol.ru/rss` - SSL cert is valid, but when I add it to spaRSS client (or any fork of spaRSS), i got error message:

```
Error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```

I use latest version from F-Droid

Could you fix that, please?
PS: other RSS clients (eg: Feeder) works with that url without issues
PPS: I got the same issue with some other feeds, but didn't save urls to attach here

**Comment by 39aldo39** [comment]
I tried your link as well, but it did work for me. In the original spaRSS version I do get your error message, but not in spaRSS DecSync. What is your device and Android version?

**Comment by rakshazi** [comment]
LineageOS 16
But I tried that link now and it works, seems it has been fixed.

thank you!
