### ISSUE TITLE
Proxy settings unselectable.

### ISSUE THREAD

**Issue by ghost** [39aldo39/spaRSS-DecSync#13]
With version 1.15.0 and later, the Proxy setting under Network in the main settings menu is not selectable. When I select it, it highlights briefly but never goes into the proxy settings. If the proxy settings are set before upgrading to 1.15.0 or later, the proxy continues working, you just can't change the settings.

I'm using the F-Droid versions on LineageOS 17.1.

**Comment by 39aldo39** [comment]
Thanks for the notice! It is fixed now.
