### ISSUE TITLE
Mark Read

### ISSUE THREAD

**Issue by cwmke** [39aldo39/spaRSS-DecSync#3]
I just stumbled onto this project and it looks great! I'm wondering if "mark read on scroll" or "mark above read" might be implemented? 

On scroll marks articles read as you scroll past them. Mark above read usually requires a long press followed by tapping "Mark Above Read."

**Comment by 39aldo39** [comment]
I'm afraid it won't be implemented. I created this fork to add synchronization to spaRSS, but I'm not really interested in maintaining the application itself on top of it. I will look a bit into crashes or serious bugs, but not really into feature requests. Unfortunately, the original author also doesn't maintain it anymore. So, unless someone makes a pull request, it probably won't be implemented.

**Comment by cwmke** [comment]
Sounds good. Thanks anyways!
