### ISSUE TITLE
Cannot select opml file for importing

### ISSUE THREAD

**Issue by kuanyui** [39aldo39/spaRSS-DecSync#4]
After pressing "Import OPML", it jumps out Android's file select page. However, all files are not clickable, including .xml and .opml.
![screenshot_20190228-221004](https://user-images.githubusercontent.com/1370070/53572412-26054400-3ba6-11e9-81f6-01af784d795f.jpg)

**Comment by 39aldo39** [comment]
Thanks for the report! It should be fixed now.

**Comment by kuanyui** [comment]
Wow, so scaring efficient! Thanks!

When is this version available on F-Droid?

**Comment by 39aldo39** [comment]
It should be available on F-Droid in around 1-2 days. As a workaround, you can actually place the OPML file in to root of the internal storage. After cancelling the file selection, spaRSS will list those files and allows you to import one.
