### ISSUE TITLE
Automatic refesh does not work

### ISSUE THREAD

**Issue by joelthetroll** [39aldo39/spaRSS-DecSync#5]
Version 1.13.4
on LineageOS 15.1

The setting "Enable automatic refresh" is checked. I expect the app to automatically refresh the feeds at the refresh interval specified. Instead, the device only refreshes when I hit the button to reload feeds.

Thanks.

**Comment by 39aldo39** [comment]
This probably has to do with [Doze or App Standby](https://developer.android.com/training/monitoring-device-state/doze-standby). You can add an exception to spaRSS DecSync with the steps described [here](https://android.gadgethacks.com/how-to/android-basics-disable-doze-app-standby-for-individual-apps-0168960/). I will look for a better solution later.

**Comment by joelthetroll** [comment]
Thanks for the help. I tried this but it didn't resolve the issue.

**Comment by joelthetroll** [comment]
I realized some more detail: the feeds now refresh in the background but notifications do not appear.

**Comment by poperigby** [comment]
I'm also having this issue. Anything I can do to help?

**Comment by 39aldo39** [comment]
Don't the feeds refresh for you or are just the notifications not appearing?

**Comment by poperigby** [comment]
I'm getting notifications now for some reason. I still have to keep battery optimization off though.

**Comment by 39aldo39** [comment]
Automatic refresh is fixed in v1.15.0!
