### ISSUE TITLE
Feature Request: Encrypt DecSync Feed File(s)

### ISSUE THREAD

**Issue by trymeouteh** [39aldo39/spaRSS-DecSync#7]
DecSync is what I love about this app. It allows me to use Syncthing to sync my feeds between devices and not rely on any server.

To enhance user security and privacy please add an option encrypt the DecSync file(s) so when the file(s) are stored on the users device and when it is in transit it will be encrypted even if the user uses an non-encrypted syncing tool or if the users device is compromised.

**Comment by 39aldo39** [comment]
Indeed, encryption support is nice, I'm already working on it! See also 39aldo39/DecSync#4. Closing this in favor of that.
