### ISSUE TITLE
Feature Request: Add Facebook/Twitter Feeds

### ISSUE THREAD

**Issue by trymeouteh** [39aldo39/spaRSS-DecSync#8]
I understand this is an RSS app, but I don't have facebook or a twitter account. But I like to "follow" certain pages since many businesses have a facebook page or a twitter page which is public and can be viewed without an account. These social media pages do not support RSS (Apparently they did back then but removed RSS functionality).

With this feature people can get updates on tweets and facebook posts without using facebook or twitter.

**Comment by 39aldo39** [comment]
I can see why you would want to add Facebook and Twitter feeds, but it is not in the scope of this app, which is a RSS reader. I think there are services which convert a Facebook or Twitter feed to a RSS feed. Maybe it is possible to use one of those?

**Comment by trymeouteh** [comment]
There are FB/TW to RSS converters but they cost money to use. I understand implementing this would be quite some work but I figured it would be better to do it through an app since the app can scan the FB/TW webpage and then sort the tweets or posts info a feed.

Essentially you will save the URL in the app, and everytime the app refreshes it will look at the page for the latest tweet/post and see if it matches the latest tweet/post that is saved in the app. If not it will fetch the post and save it in the app and notify the user of the new post. It will be simular to how NewPipe pareses YouTube URLs.

**Comment by smnthermes** [comment]
@trymeouteh you can use RSS-Bridge for Facebook. Edit: for Twitter, you can use Nitter, which is a complete proxy.
